# tasks file
---
- name: set system file descriptor limit
  sysctl:
    name: fs.file-max
    value: "{{ memcached_fs_file_max }}"
    reload: true
    state: present
  when: memcached_fs_file_max
  tags:
    - configuration
    - memcached
    - memcached-fs-file-max

- name: set system ip port limits
  sysctl:
    name: net.ipv4.ip_local_port_range
    value: "{{ memcached_net_ipv4_ip_local_port_range }}"
    reload: true
    state: present
  when: memcached_net_ipv4_ip_local_port_range
  tags:
    - configuration
    - memcached
    - memcached-local-port-range

- name: install package
  apt:
    name: "{{ memcached_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - configuration
    - memcached
    - memcached-install

- name: update configuration file(s)
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - src: "{{ memcached_etc_default_file.lstrip('/') }}.j2"
      dest: "{{ memcached_etc_default_file }}"
    - src: "{{ memcached_etc_conf_file.lstrip('/') }}.j2"
      dest: "{{ memcached_etc_conf_file }}"
  notify: restart memcached
  tags:
    - configuration
    - memcached
    - memcached-configuration

- include: service-initd.yml
  when: ansible_service_mgr != 'systemd'
  tags:
    - configuration
    - memcached
    - memcached-configure
    - memcached-configure-initd

- include: service-systemd.yml
  when: ansible_service_mgr == 'systemd'
  tags:
    - configuration
    - memcached
    - memcached-configure
    - memcached-configure-systemd

- name: start and enable service
  service:
    name: memcached
    state: "{{ service_default_state | default('started') }}"
    enabled: "{{ service_default_enabled | default(true) | bool }}"
  tags:
    - configuration
    - memcached
    - memcached-start-enable-service
