# tasks file for memcached
---
- name: install package
  apt:
    name: memcached
    state: latest
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags: [configuration, memcached, memcached-install]

- name: update configuration file
  template:
    src: etc/memcached.conf.j2
    dest: /etc/memcached.conf
    owner: root
    group: root
    mode: 0644
  notify: restart memcached
  tags: [configuration, memcached, memcached-configuration]

- name: set system file descriptor limit
  sysctl:
    name: fs.file-max
    value: "{{ memcached_fs_file_max }}"
    reload: true
    state: present
  when: memcached_fs_file_max != false
  tags: [configuration, memcached, memcached-fs-file-max]

- name: set system ip port limits
  sysctl:
    name: net.ipv4.ip_local_port_range
    value: "{{ memcached_net_ipv4_ip_local_port_range }}"
    reload: true
    state: present
  when: memcached_net_ipv4_ip_local_port_range != false
  tags: [configuration, memcached, memcached-local-port-range]

- name: start and enable service
  service:
    name: memcached
    state: started
    enabled: true
  tags: [configuration, memcached, memcached-start-enable-service]
