---
- name: Verify
  hosts: all
  become: true
  tasks:
    - name: include vars
      include_vars: "{{ playbook_dir }}/../../defaults/main.yml"
    - name: include tasks
      include: "{{ playbook_dir }}/../../tests/tasks/post.yml"
